action_horizon: 8
pred_horizon: 16
# pred_horizon: 32
obs_horizon: 1
predict_past_actions: false # whether executable actions start from the past
parts_poses_in_robot_frame: false
task: one_leg
observation_type: state
environment: sim
demo_source: teleop
randomness: low
discount: 0.999
demo_outcome: success
control:
  act_rot_repr: rot_6d
  control_mode: pos
  controller: diffik
wandb:
  project: action-vqvae-${task}-${randomness}-${pred_horizon}
  notes: null
  mode: online # online | offline | disable
  continue_run_id: null
  name: null
  watch_model: false
  osh_sync_interval: 25
  entity: zhefeigong
dryrun: false
vqvae:
  act_horizon: ${pred_horizon}
  vocab_size: 512
  vocab_ch: 8
  vch: 2
  act_dim_sep: 0
  patch_nums: [1, 2, 3, 4]
  # patch_nums: [1, 3, 6, 8]
  vqbeta: 0.25
  vqnorm: True
  vqresi: 0.5
  vae_init: -0.5
  vocab_init: -1
  vopt_beta: '0.5_0.9'
  opt: 'adamw'
  ac: 1
  vblr: 3e-4
  vlr: ${eval:'${vqvae.ac} * ${vqvae.vblr} * ${training.batch_size} / 256'}
  vwp: ${eval:'${training.num_epochs} * 1/50'} 
  vwp0: 0.005
  vwpe: 0.3
  vsche: 'cos'
  vwd: 0.005
  vwde: 0
  vdrop: 0.0
  fp16: 0
  tf32: True
  afuse: True
  vclip: 10.
  vema: 0.9999
  act_dim_names: ['x','y','z','r1','r2','r3','r4','r5','r6','gripper']
training:
  gpu_id: 0
  warmup_step: null # -> assigned in the code
  max_global_step: null # -> assigned in the code
  num_epochs: 500
  batch_size: 256
  start_epoch: 0
  steps_per_epoch: 1000
  eval_every: 10
  model_save_dir: models
  checkpoint_interval: 50
  store_best_test_loss_model: true
  store_last_model: true
  store_best_success_rate_model: true
data:
  test_split: 0.05
  data_subset: null
  dataloader_workers: 16
  pred_horizon: ${pred_horizon}
  obs_horizon: ${obs_horizon}
  action_horizon: ${action_horizon}
  predict_past_actions: ${predict_past_actions}
  augment_image: true
  environment: ${environment}
  task: ${task}
  demo_source: ${demo_source}
  randomness: ${randomness}
  normalization: min_max
  demo_outcome: ${demo_outcome}
  pad_after: true
  suffix: null
  include_future_obs: false
  minority_class_power: false
  data_paths_override: null
  load_into_memory: true
  parts_poses_in_robot_frame: ${parts_poses_in_robot_frame}

